//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teema
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationGroupMember
    {
        public int Id { get; set; }
        public int NotificationGroupId { get; set; }
        public int SourceId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual NotificationGroup NotificationGroup { get; set; }
        public virtual User User { get; set; }
    }
}
